name: Deploy to Staging Environment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  app_deploy:
    name: Build and deploy application
    if: ${{ github.repository == 'sws2apps/sws2apps-console' && github.ref == 'refs/heads/main' }}
    environment:
      name: Staging
      url: https://staging-console.sws2apps.com
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Use Node.js LTS version
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: lts/Iron

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy project to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
