name: Scorecards

on:
  branch_protection_rule:
  schedule:
    - cron: '0 12 * * 4'
  push:
    branches: [main]

permissions: read-all

jobs:
  scorecards:
    name: Scorecards Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: false

      - name: 'Run analysis'
        uses: ossf/scorecard-action@5c8bc69dc88b65c66584e07611df79d3579b0377
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: 'Upload to code-scanning'
        uses: github/codeql-action/upload-sarif@1ed1437484560351c5be56cf73a48a279d116b78
        with:
          sarif_file: results.sarif
